version: '3.8'
services:
  # BlueSalt Services

    # Customer Service
    customer_service:
      container_name: "bluesalt_customer"
      restart: unless-stopped
      build:
        context: ./customer
        dockerfile: Dockerfile
      ports:
        - "1010:1010"

    # Billing Service
    billing_service:
      container_name: "bluesalt_billing"
      restart: unless-stopped
      build:
        context: ./billing
        dockerfile: Dockerfile
      ports:
        - "4040:4040"

    # Worker Service
    worker_service:
      container_name: "bluesalt_worker"
      restart: unless-stopped
      build:
        context: ./billing_worker
        dockerfile: Dockerfile


    # RabbitMQ Service
    rabbitmq3:
      container_name: "bluesalt_queue"
      restart: unless-stopped
      image: rabbitmq:3-management
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      ports:
        - "5672:5672"    # AMQP protocol port
        - "15672:15672"  # HTTP management UI
        - "15692:15692"  # HTTP Prometheus
        - "25672:25672"  # Clustering

    # MongoDB Service
    mongodb:
      image: mongo:latest # use the latest image.
      container_name: bluesalt_mongoDB
      restart: unless-stopped
      environment: # set required env variables to access mongo
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
      ports:
        - 27017:27017
      # volumes: # optional to preserve database after container is deleted.
        # - ./database-data:/data/db

